sudo: false
language: ruby
rvm:
  - 2.7
  - 2.6
  - 2.5
  - 2.4
  - ruby-head
env:
  - 'JEKYLL_VERSION="~> 3.0"'
  - 'JEKYLL_VERSION="~> 4.0"'
matrix:
  allow_failures:
    - rvm: ruby-head
before_install: gem install bundler
script: bundle exec rspec
